#!/usr/bin/env node
// Derives the UI's JSON from a brief markdown file, so the markdown stays the
// single source of truth.
//   node scripts/brief-to-json.mjs briefs/2026-08-15-am.md
//   node scripts/brief-to-json.mjs --index   (rebuild briefs/INDEX.md only)
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";

const path = process.argv[2];
if (!path) {
  console.error(
    "usage: node scripts/brief-to-json.mjs <brief.md> | --index | --performance | --friends"
  );
  process.exit(1);
}

// The de-duplication index. A scan only needs to know which stories and tools
// have already run, not their material — and briefs are ~58KB each now, so
// reading six of them costs ~87k tokens of context that gets replayed on every
// turn of the run. One line per idea is the same information for ~2% of that.
//
// Capped to the most recent dates. The index sits in the baseline context and is
// replayed on every turn, so an uncapped one grows into exactly the cost it was
// built to avoid — ~594KB and ~149k tokens after a year. The skill reads the six
// most recent dates; 14 is slack on top of that.
const KEEP_DATES = 14;

function buildIndex(briefsDir) {
  const line = (s, n) => (s ?? "").replace(/\s+/g, " ").trim().slice(0, n);
  const byDate = new Map();
  for (const f of readdirSync(briefsDir).filter((f) => f.endsWith(".json"))) {
    let doc;
    try { doc = JSON.parse(readFileSync(join(briefsDir, f), "utf8")); } catch { continue; }
    const date = (f.match(/^(\d{4}-\d{2}-\d{2})/) ?? [])[1];
    if (!date || !doc.ideas?.length) continue;
    const rows = doc.ideas.map((i) => {
      const rate = i.rating === "up" ? " · +" : i.rating === "down" ? " · -" : "";
      // Explainers carry no lead paragraph — their script's opening sentence
      // names the subject and the misconception, which is the angle.
      const why = line(i.why || i.script || i.hook || i.note, 110);
      return `${i.id} ${i.bucket} · ${line(i.title, 90)}${why ? ` · ${why}` : ""}${rate}${
        i.ratingReason ? ` (${line(i.ratingReason, 70)})` : ""}`;
    });
    // Two runs can share a date (`-am`, `-cloud`); keep both under the one heading.
    byDate.set(date, (byDate.get(date) ?? []).concat(rows));
  }
  const dates = [...byDate.keys()].sort().reverse().slice(0, KEEP_DATES);
  const out = [
    "# Brief index",
    "",
    "One line per idea, newest first — the de-duplication surface for a scan.",
    "Generated by `scripts/brief-to-json.mjs`; do not edit by hand.",
    "",
    ...dates.flatMap((d) => [`## ${d}`, "", ...byDate.get(d).map((r) => `- ${r}`), ""]),
  ].join("\n");
  const dest = join(briefsDir, "INDEX.md");
  writeFileSync(dest, out);
  return { dest, dates: dates.length, ideas: dates.reduce((n, d) => n + byDate.get(d).length, 0) };
}

// The performance log: published videos and the read on each, plus the
// **Patterns** block distilled from them. Same md-is-the-source-of-truth deal as
// a brief — the reader shows this, `agent/taste.md` encodes it, and only the
// markdown is edited by hand.
function buildPerformance(src = "agent/performance.md") {
  const md = readFileSync(src, "utf8");
  const chunks = md.split(/^## /m).slice(1);
  const videos = [];
  let patterns = [];

  for (const chunk of chunks) {
    const title = chunk.split("\n")[0].trim();
    const field = (label) => {
      const m = chunk.match(
        new RegExp(`\\*\\*${label}\\*\\*([^\\n]*)\\n((?:(?!\\*\\*|## )[^\\n]*\\n?)*)`, "i")
      );
      if (!m) return null;
      // A field's prose may wrap across lines; it is one value either way. The
      // last field in an entry runs up to the `---` rule before the next one,
      // which is a separator rather than content.
      return (
        (m[1].trim() + " " + (m[2] || "").trim())
          .replace(/\s+/g, " ")
          .replace(/\s*-{3,}\s*$/, "")
          .trim() || null
      );
    };

    // An entry is a video only if it carries a view count. Everything else under
    // a `## ` heading is prose — the Patterns block is the one that matters.
    const rawViews = field("Views");
    if (!rawViews) {
      if (/^patterns/i.test(title)) {
        // A pattern is one bullet, hard-wrapped across as many lines as it
        // takes — the file is written to be read in an editor. Continuation
        // lines are indented, so they fold back into the bullet above.
        for (const raw of chunk.split("\n")) {
          if (raw.startsWith("- ")) patterns.push(raw.slice(2).trim());
          else if (/^\s+\S/.test(raw) && patterns.length) {
            patterns[patterns.length - 1] += ` ${raw.trim()}`;
          } else if (!raw.trim()) {
            // A blank line ends the list; anything after it is prose.
            if (patterns.length) break;
          }
        }
        patterns = patterns.map((t) => t.replace(/\s+/g, " ").trim()).filter(Boolean);
      }
      continue;
    }

    // The quoted comments, with their like counts. They are the evidence the
    // read is written from, so they ship alongside it rather than being
    // summarised away.
    const topComments = (chunk.match(/\*\*Top comments\*\*[^\n]*\n((?:- [^\n]*\n?)*)/) ?? [])[1]
      ?.split("\n")
      .filter((l) => l.startsWith("- "))
      .map((l) => l.slice(2).trim())
      .filter(Boolean) ?? [];

    videos.push({
      title,
      platform: field("Platform"),
      posted: field("Posted"),
      views: Number((rawViews.match(/[\d,]+/)?.[0] ?? "").replace(/,/g, "")) || null,
      viewsLabel: rawViews,
      engagement: field("Engagement"),
      topComments,
      format: (field("Format") ?? "").split("·").map((t) => t.trim()).filter(Boolean),
      hook: field("Hook used"),
      comments: field("What the comments did"),
      why: field("Why it worked"),
      repeat: field("Repeat it by"),
      link: field("Link"),
    });
  }

  videos.sort((a, b) => (b.views ?? 0) - (a.views ?? 0));
  const dest = src.replace(/\.md$/, ".json");
  writeFileSync(dest, JSON.stringify({ patterns, videos }, null, 2));
  return { dest, videos: videos.length, patterns: patterns.length };
}

// Channels worth learning from, and the device to take from each. Same
// md-is-the-truth deal as the performance log.
function buildFriends(src = "agent/friends.md") {
  const md = readFileSync(src, "utf8");
  const bullets = (chunk, label) =>
    ((chunk.match(new RegExp(`\\*\\*${label}\\*\\*[^\\n]*\\n((?:- [^\\n]*\\n?)*)`)) ?? [])[1] ?? "")
      .split("\n")
      .filter((l) => l.startsWith("- "))
      .map((l) => l.slice(2).trim())
      .filter(Boolean);

  const channels = [];
  let devices = [];
  for (const chunk of md.split(/^## /m).slice(1)) {
    const title = chunk.split("\n")[0].trim();
    const field = (label) => {
      const m = chunk.match(
        new RegExp(`\\*\\*${label}\\*\\*([^\\n]*)\\n((?:(?!\\*\\*|## |- )[^\\n]*\\n?)*)`, "i")
      );
      if (!m) return null;
      return (
        (m[1].trim() + " " + (m[2] || "").trim())
          .replace(/\s+/g, " ")
          .replace(/\s*-{3,}\s*$/, "")
          .trim() || null
      );
    };
    if (!field("Reach")) {
      // The cross-channel findings live under their own heading, as one bullet
      // each, wrapped across lines the way the file is written to be read.
      if (/^devices/i.test(title)) {
        const out = [];
        for (const raw of chunk.split("\n")) {
          if (raw.startsWith("- ")) out.push(raw.slice(2).trim());
          else if (/^\s+\S/.test(raw) && out.length) out[out.length - 1] += ` ${raw.trim()}`;
          else if (!raw.trim() && out.length) break;
        }
        devices = out.map((t) => t.replace(/\s+/g, " ").trim()).filter(Boolean);
      }
      continue;
    }
    // `### ` blocks inside a channel are individual videos, studied frame by
    // frame. They are the point of the file — the channel fields are context.
    const videos = chunk.split(/^### /m).slice(1).map((vc) => {
      const vTitle = vc.split("\n")[0].trim();
      const vField = (label) => {
        const m = vc.match(
          new RegExp(`\\*\\*${label}\\*\\*([^\\n]*)\\n((?:(?!\\*\\*|#{2,3} |- )[^\\n]*\\n?)*)`, "i")
        );
        if (!m) return null;
        return (
          (m[1].trim() + " " + (m[2] || "").trim())
            .replace(/\s+/g, " ")
            .replace(/\s*-{3,}\s*$/, "")
            .trim() || null
        );
      };
      return {
        title: vTitle,
        numbers: vField("Numbers"),
        onScreen: vField("On-screen hook"),
        spoken: vField("Spoken open") || vField("Caption"),
        caption: vField("Spoken open") ? vField("Caption") : null,
        what: vField("What it actually is"),
        beats: bullets(vc, "Beats"),
        steal: vField("Steal"),
      };
    });

    channels.push({
      handle: title.replace(/^@/, ""),
      videos,
      profile: field("Profile"),
      reach: field("Reach"),
      model: field("The model"),
      steal: bullets(chunk, "Steal this"),
      avoid: field("Don't copy"),
      posts: bullets(chunk, "Best posts"),
      note: field("Note"),
      link: field("Link"),
    });
  }
  const dest = src.replace(/\.md$/, ".json");
  writeFileSync(dest, JSON.stringify({ devices, channels }, null, 2));
  return { dest, channels: channels.length, devices: devices.length };
}

if (path === "--friends") {
  const r = buildFriends();
  console.log(`${r.dest} — ${r.channels} channels, ${r.devices} devices`);
  process.exit(0);
}

if (path === "--performance") {
  const r = buildPerformance();
  console.log(`${r.dest} — ${r.videos} videos, ${r.patterns} patterns`);
  process.exit(0);
}

if (path === "--index") {
  const r = buildIndex("briefs");
  console.log(`${r.dest} — ${r.ideas} ideas across ${r.dates} dates`);
  process.exit(0);
}

const md = readFileSync(path, "utf8");
const BUCKETS = { A: "news", B: "tutorial", C: "explainer", D: "longform" };

const header = md.match(/^# (.*)/m)?.[1] ?? "";
const ideas = [];

// Each idea starts at "## A1 · NEWS · Title" (D1 · LONGFORM for the YouTube idea)
const chunks = md.split(/^## /m).slice(1);
for (const chunk of chunks) {
  const head = chunk.split("\n")[0];
  const m = head.match(/^([ABCD])(\d+)\s*·\s*[^·]+·\s*(.+)$/);
  if (!m) continue;
  const [, letter, num, title] = m;

  // A field's value is either on the same line as its label
  // (`**Time to build** 10 minutes`) or in the block beneath it.
  const field = (label) => {
    const re = new RegExp(`\\*\\*${label}\\*\\*([^\\n]*)\\n((?:(?!\\*\\*|## )[^\\n]*\\n?)*)`, "i");
    const m = chunk.match(re);
    if (!m) return null;
    const sameLine = m[1].replace(/^\s*\(.*?\)\s*/, "").trim(); // drop "(0-3s)" annotations
    const below = (m[2] || "").trim().replace(/^>\s*/gm, "");
    return sameLine || below || null;
  };

  // Short-form beats are "0-3s"; Bucket D chapters are "0:00-0:45". Both land in `beats`.
  const beats = [...chunk.matchAll(/^- (\d+:\d{2}-\d+:\d{2}|\d+-\d+s) — (.*)$/gm)]
    .map((b) => ({ t: b[1], text: b[2] }));
  // Scoped to the Sources block — the material bullets are also "- ..." lines
  // and must not be mistaken for sources.
  const sourceBlock = chunk.match(/\*\*Sources\*\*[^\n]*\n((?:(?!\*\*|## )[\s\S])*)/);
  const sources = [...(sourceBlock?.[1] ?? "").matchAll(/^- (.+?) — (https?:\/\/\S+)$/gm)]
    .map((s) => ({ name: s[1], url: s[2] }));

  // Bucket C ships the finished script instead of material. Paragraphs are
  // blank-line separated and stay that way — the UI and the email both split
  // on that, and a script rendered as one block is unreadable to read from.
  const script = (() => {
    const m = chunk.match(/\*\*The script\*\*[^\n]*\n([\s\S]*?)(?=\n\*\*|\n## |\n---|$)/);
    if (!m) return null;
    return m[1].split("\n").map((l) => l.trim()).join("\n").trim() || null;
  })();

  // The upload-box hashtags, stored bare so the UI owns the "#". One line,
  // space separated; briefs written before the field existed simply have none.
  // `\w` is the tag exactly as a platform reads it — a hyphen or a space ends a
  // hashtag everywhere it gets pasted, so `#sports-betting` really is `#sports`.
  const tags = [...new Set(
    [...(chunk.match(/\*\*Tags\*\*([^\n]*)/i)?.[1] ?? "").matchAll(/#(\w+)/g)]
      .map((t) => t[1].toLowerCase())
  )];

  // Six to ten alternate opening lines, `- {type} — {line}`. The first is the
  // script's opening sentence; the rest are swaps, so order is meaning here and
  // the list is not deduped or sorted. Scoped to its own block, because sources
  // and material are `- ` lines too, and split on the first em dash only — a
  // hook is allowed to contain one.
  const hookBlock = chunk.match(/\*\*Hooks\*\*[^\n]*\n((?:(?!\*\*|## )[\s\S])*)/);
  const hooks = [...(hookBlock?.[1] ?? "").matchAll(/^- (.+)$/gm)]
    .map((h) => {
      const parts = h[1].match(/^(.+?)\s+—\s+(.+)$/);
      return parts
        ? { type: parts[1].trim().toLowerCase(), text: parts[2].trim() }
        : { type: null, text: h[1].trim() };
    })
    .filter((h) => h.text);

  // The raw fact list. Deliberately long — Lana picks from it to write the script.
  const materialBlock = chunk.match(/\*\*The material\*\*[^\n]*\n((?:- [\s\S]*?)?)(?=\n\*\*|\n## |$)/);
  const material = (materialBlock?.[1] ?? "")
    .split("\n")
    .filter((l) => l.startsWith("- "))
    .map((l) => l.slice(2).trim())
    .filter(Boolean);

  const extra = {};
  for (const label of ["What you build", "Time to build", "How you set it up",
                       "The money shot", "Where else this applies", "Gotchas",
                       "The misconception", "The analogy", "Where it breaks",
                       "Where the analogy breaks", "Pairs with",
                       "The thesis", "Why it holds ten minutes", "What you'd need", "Thumbnail"]) {
    const v = field(label);
    if (v) extra[label] = v;
  }

  // Bucket D lists candidate YouTube titles as bare bullets under "Title options".
  const titleBlock = chunk.match(/\*\*Title options\*\*[^\n]*\n+((?:- .*\n?)+)/);
  const titleOptions = titleBlock
    ? titleBlock[1].split("\n").map((l) => l.replace(/^- /, "").trim()).filter(Boolean)
    : [];

  // The thesis is promoted to `why` only on older briefs that have no lead
  // paragraphs above it. Where "What this is" leads, the thesis stays a field.
  if (letter === "D" && !field("What this is") && !field("Why it's good")) {
    delete extra["The thesis"];
  }

  // `rate: + reason` and `` `rate: +` reason `` are both in use — the reason
  // is the point of the rating, so read it from inside or after the backticks.
  const rateLine = chunk.match(/`rate:\s*([+-]?)([^`]*)`[ \t]*([^\n]*)/);
  const symbol = rateLine?.[1]?.trim() || null;
  const reason = (rateLine?.[2]?.trim() || rateLine?.[3]?.trim() || "")
    .replace(/^←.*/, "")
    .trim();

  ideas.push({
    id: `${letter}${num}`,
    bucket: BUCKETS[letter],
    title: title.trim(),
    // Bucket D's `**Hook**` is the 0-15s cold open and stays a single field;
    // `**Hooks**` is the menu, and every bucket carries one. The label regex
    // below is exact, so the plural never lands in `hook`.
    hook: field("Hook"),
    hooks,
    // "What this is" is the current lead field; the other two are older briefs.
    why: field("What this is") || field("Why it's good")
      || (letter === "D" ? field("The thesis") : null),
    script,
    beats,
    material,
    sources,
    tags,
    freshness: chunk.match(/\*\*Freshness\*\*\s*([^·\n]+)/)?.[1].trim() || null,
    saturation: chunk.match(/\*\*Saturation\*\*\s*([^\n]+)/)?.[1].trim() || null,
    note: chunk.match(/^> note:\s*(.+)$/m)?.[1] || null,
    // `**Status** done` is set from the reader when a video is finished. It is
    // deliberately separate from the rating: keeping an idea is a judgment,
    // finishing it is a fact, and an idea can be both.
    status: (field("Status") ?? "").toLowerCase().trim() || null,
    rating: symbol === "+" ? "up" : symbol === "-" ? "down" : null,
    ratingReason: reason || null,
    extra,
    ...(titleOptions.length ? { titleOptions } : {}),
  });
}

const out = { title: header, slug: path.replace(/.*\//, "").replace(/\.md$/, ""), generated: header, ideas };
const dest = path.replace(/\.md$/, ".json");
writeFileSync(dest, JSON.stringify(out, null, 2));
console.log(`${dest} — ${ideas.length} ideas (${ideas.filter(i => i.rating).length} rated)`);

const idx = buildIndex(dirname(dest) || ".");
console.log(`${idx.dest} — ${idx.ideas} ideas across ${idx.dates} dates`);
