#!/usr/bin/env node
// Derives the UI's JSON from a brief markdown file, so the markdown stays the
// single source of truth.
//   node scripts/brief-to-json.mjs briefs/2026-08-15-am.md
//   node scripts/brief-to-json.mjs --index   (rebuild briefs/INDEX.md only)
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";

const path = process.argv[2];
if (!path) { console.error("usage: node scripts/brief-to-json.mjs <brief.md> | --index"); process.exit(1); }

// The de-duplication index. A scan only needs to know which stories and tools
// have already run, not their material — and briefs are ~58KB each now, so
// reading six of them costs ~87k tokens of context that gets replayed on every
// turn of the run. One line per idea is the same information for ~2% of that.
//
// Capped to the most recent dates. The index sits in the baseline context and is
// replayed on every turn, so an uncapped one grows into exactly the cost it was
// built to avoid — ~594KB and ~149k tokens after a year. The skill reads the six
// most recent dates; 14 is slack on top of that.
const KEEP_DATES = 14;

function buildIndex(briefsDir) {
  const line = (s, n) => (s ?? "").replace(/\s+/g, " ").trim().slice(0, n);
  const byDate = new Map();
  for (const f of readdirSync(briefsDir).filter((f) => f.endsWith(".json"))) {
    let doc;
    try { doc = JSON.parse(readFileSync(join(briefsDir, f), "utf8")); } catch { continue; }
    const date = (f.match(/^(\d{4}-\d{2}-\d{2})/) ?? [])[1];
    if (!date || !doc.ideas?.length) continue;
    const rows = doc.ideas.map((i) => {
      const rate = i.rating === "up" ? " · +" : i.rating === "down" ? " · -" : "";
      // Explainers carry no lead paragraph — their script's opening sentence
      // names the subject and the misconception, which is the angle.
      const why = line(i.why || i.script || i.hook || i.note, 110);
      return `${i.id} ${i.bucket} · ${line(i.title, 90)}${why ? ` · ${why}` : ""}${rate}${
        i.ratingReason ? ` (${line(i.ratingReason, 70)})` : ""}`;
    });
    // Two runs can share a date (`-am`, `-cloud`); keep both under the one heading.
    byDate.set(date, (byDate.get(date) ?? []).concat(rows));
  }
  const dates = [...byDate.keys()].sort().reverse().slice(0, KEEP_DATES);
  const out = [
    "# Brief index",
    "",
    "One line per idea, newest first — the de-duplication surface for a scan.",
    "Generated by `scripts/brief-to-json.mjs`; do not edit by hand.",
    "",
    ...dates.flatMap((d) => [`## ${d}`, "", ...byDate.get(d).map((r) => `- ${r}`), ""]),
  ].join("\n");
  const dest = join(briefsDir, "INDEX.md");
  writeFileSync(dest, out);
  return { dest, dates: dates.length, ideas: dates.reduce((n, d) => n + byDate.get(d).length, 0) };
}

if (path === "--index") {
  const r = buildIndex("briefs");
  console.log(`${r.dest} — ${r.ideas} ideas across ${r.dates} dates`);
  process.exit(0);
}

const md = readFileSync(path, "utf8");
const BUCKETS = { A: "news", B: "tutorial", C: "explainer", D: "longform" };

const header = md.match(/^# (.*)/m)?.[1] ?? "";
const ideas = [];

// Each idea starts at "## A1 · NEWS · Title" (D1 · LONGFORM for the YouTube idea)
const chunks = md.split(/^## /m).slice(1);
for (const chunk of chunks) {
  const head = chunk.split("\n")[0];
  const m = head.match(/^([ABCD])(\d+)\s*·\s*[^·]+·\s*(.+)$/);
  if (!m) continue;
  const [, letter, num, title] = m;

  // A field's value is either on the same line as its label
  // (`**Time to build** 10 minutes`) or in the block beneath it.
  const field = (label) => {
    const re = new RegExp(`\\*\\*${label}\\*\\*([^\\n]*)\\n((?:(?!\\*\\*|## )[^\\n]*\\n?)*)`, "i");
    const m = chunk.match(re);
    if (!m) return null;
    const sameLine = m[1].replace(/^\s*\(.*?\)\s*/, "").trim(); // drop "(0-3s)" annotations
    const below = (m[2] || "").trim().replace(/^>\s*/gm, "");
    return sameLine || below || null;
  };

  // Short-form beats are "0-3s"; Bucket D chapters are "0:00-0:45". Both land in `beats`.
  const beats = [...chunk.matchAll(/^- (\d+:\d{2}-\d+:\d{2}|\d+-\d+s) — (.*)$/gm)]
    .map((b) => ({ t: b[1], text: b[2] }));
  // Scoped to the Sources block — the material bullets are also "- ..." lines
  // and must not be mistaken for sources.
  const sourceBlock = chunk.match(/\*\*Sources\*\*[^\n]*\n((?:(?!\*\*|## )[\s\S])*)/);
  const sources = [...(sourceBlock?.[1] ?? "").matchAll(/^- (.+?) — (https?:\/\/\S+)$/gm)]
    .map((s) => ({ name: s[1], url: s[2] }));

  // Bucket C ships the finished script instead of material. Paragraphs are
  // blank-line separated and stay that way — the UI and the email both split
  // on that, and a script rendered as one block is unreadable to read from.
  const script = (() => {
    const m = chunk.match(/\*\*The script\*\*[^\n]*\n([\s\S]*?)(?=\n\*\*|\n## |\n---|$)/);
    if (!m) return null;
    return m[1].split("\n").map((l) => l.trim()).join("\n").trim() || null;
  })();

  // The upload-box hashtags, stored bare so the UI owns the "#". One line,
  // space separated; briefs written before the field existed simply have none.
  // `\w` is the tag exactly as a platform reads it — a hyphen or a space ends a
  // hashtag everywhere it gets pasted, so `#sports-betting` really is `#sports`.
  const tags = [...new Set(
    [...(chunk.match(/\*\*Tags\*\*([^\n]*)/i)?.[1] ?? "").matchAll(/#(\w+)/g)]
      .map((t) => t[1].toLowerCase())
  )];

  // The raw fact list. Deliberately long — Lana picks from it to write the script.
  const materialBlock = chunk.match(/\*\*The material\*\*[^\n]*\n((?:- [\s\S]*?)?)(?=\n\*\*|\n## |$)/);
  const material = (materialBlock?.[1] ?? "")
    .split("\n")
    .filter((l) => l.startsWith("- "))
    .map((l) => l.slice(2).trim())
    .filter(Boolean);

  const extra = {};
  for (const label of ["What you build", "Time to build", "How you set it up",
                       "The money shot", "Where else this applies", "Gotchas",
                       "The misconception", "The analogy", "Where it breaks",
                       "Where the analogy breaks", "Pairs with",
                       "The thesis", "Why it holds ten minutes", "What you'd need", "Thumbnail"]) {
    const v = field(label);
    if (v) extra[label] = v;
  }

  // Bucket D lists candidate YouTube titles as bare bullets under "Title options".
  const titleBlock = chunk.match(/\*\*Title options\*\*[^\n]*\n+((?:- .*\n?)+)/);
  const titleOptions = titleBlock
    ? titleBlock[1].split("\n").map((l) => l.replace(/^- /, "").trim()).filter(Boolean)
    : [];

  // The thesis is promoted to `why` only on older briefs that have no lead
  // paragraphs above it. Where "What this is" leads, the thesis stays a field.
  if (letter === "D" && !field("What this is") && !field("Why it's good")) {
    delete extra["The thesis"];
  }

  // `rate: + reason` and `` `rate: +` reason `` are both in use — the reason
  // is the point of the rating, so read it from inside or after the backticks.
  const rateLine = chunk.match(/`rate:\s*([+-]?)([^`]*)`[ \t]*([^\n]*)/);
  const symbol = rateLine?.[1]?.trim() || null;
  const reason = (rateLine?.[2]?.trim() || rateLine?.[3]?.trim() || "")
    .replace(/^←.*/, "")
    .trim();

  ideas.push({
    id: `${letter}${num}`,
    bucket: BUCKETS[letter],
    title: title.trim(),
    hook: field("Hook"),
    // "What this is" is the current lead field; the other two are older briefs.
    why: field("What this is") || field("Why it's good")
      || (letter === "D" ? field("The thesis") : null),
    script,
    beats,
    material,
    sources,
    tags,
    freshness: chunk.match(/\*\*Freshness\*\*\s*([^·\n]+)/)?.[1].trim() || null,
    saturation: chunk.match(/\*\*Saturation\*\*\s*([^\n]+)/)?.[1].trim() || null,
    note: chunk.match(/^> note:\s*(.+)$/m)?.[1] || null,
    rating: symbol === "+" ? "up" : symbol === "-" ? "down" : null,
    ratingReason: reason || null,
    extra,
    ...(titleOptions.length ? { titleOptions } : {}),
  });
}

const out = { title: header, slug: path.replace(/.*\//, "").replace(/\.md$/, ""), generated: header, ideas };
const dest = path.replace(/\.md$/, ".json");
writeFileSync(dest, JSON.stringify(out, null, 2));
console.log(`${dest} — ${ideas.length} ideas (${ideas.filter(i => i.rating).length} rated)`);

const idx = buildIndex(dirname(dest) || ".");
console.log(`${idx.dest} — ${idx.ideas} ideas across ${idx.dates} dates`);
